#!/bin/bash
# vim: autoindent tabstop=4 shiftwidth=4 expandtab softtabstop=4 filetype=bash

# Return the expected test duration in seconds for rickshaw scheduling.
# Parses --duration from the benchmark parameters.

opts=$(getopt -q -o "" --longoptions "duration:" -n "getopt.sh" -- "$@");
eval set -- "$opts";
while true; do
    case "$1" in
        --duration)
            shift
            echo $1
            shift
            ;;
        --)
            shift
            exit
            ;;
        *)
            shift
            ;;
    esac
done
